# Copyright (c) 2024, libracore AG and contributors
# For license information, please see license.txt

import frappe
from frappe.model.document import Document
import erpnextswiss.erpnextswiss.attach_pdf

class TechnicalDataSheet(Document):
    def on_submit(self):
        # Attach a second PDF for use in purchasing
        # (the primary PDF for sales use is generated by the standard attach_pdf hook in utils.py)
        self.attach_po_pdf()

    def attach_po_pdf(self):
        fallback_language = frappe.db.get_single_value("System Settings", "language") or "en"
        args = {
            "doctype": self.doctype,
            "name": self.name,
            "title": self.get("title") or self.name,
            "lang": self.get("language") or fallback_language,
            "print_format": "Technical Data Sheet - Purchase Standard",
            "file_name": "{0} PO.pdf".format(self.name.replace(" ", "-").replace("/", "-"))
        }
        erpnextswiss.erpnextswiss.attach_pdf.execute(**args)

def get_current_tds(item_code):
    matching_tds = frappe.get_all("Technical Data Sheet", filters = {'item_code': item_code, 'docstatus': 1})
    if len(matching_tds) > 1:
        frappe.throw("Error: Several active TDS exist for Item '{0}'".format(item_code))
    elif len(matching_tds) == 0:
        return None
    else:
        return matching_tds[0].name
